<GridLayout>:
    cols: 1
    Label:
        text: "Comments:"
    Label:
        id: kivy_comment_1
        text: "kivy_comment_1"
    Label:
        id: kivy_comment_2
        text: "kivy_comment_2"
    Label:
        id: kivy_comment_3
        text: "kivy_comment_3"
    Label:
        id: kivy_comment_4
        text: "kivy_comment_4"
    Label:
        id: kivy_comment_5
        text: "kivy_comment_5"